default_language_version:
  python: python3.9

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      # YAML code formatter
      - id: check-yaml
      # Enforce EOF newlines
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.38.2
    hooks:
      # Upgrade outdated python syntax
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade --py38-plus
        types: [python]
        language: python

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      # Sort ordering of python imports
      - id: isort
        name: isort
        entry: isort --settings-path pyproject.toml
        types: [python]
        language: python

  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      # Run code formatting on python code
      - id: black
        name: black
        entry: black --config pyproject.toml
        types: [python]
        language: python
