site_name: PyCommonknowledge
site_url: https://commonknowledge.github.io/pycommonknowledge/
repo_url: https://github.com/commonknowledge/pycommonknowledge/
nav:
  - index.md
  - Reference:
      - Core:
        - Cache Utils: api/pyck.core.cache.md
        - Template Utils: api/pyck.core.template.md
      - Geo:
        - Map Components: components/map.components.md
  - Contributing:
      - Contribution Guidelines: contributing.md
      - Developer Setup: developing.md
      - Code Style: code-style.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - def_list
