site_name: PyCommonknowledge
site_url: https://commonknowledge.github.io/pycommonknowledge/
repo_url: https://github.com/commonknowledge/pycommonknowledge/
nav:
    - index.md
    - Contributing:
        - Contribution Guidelines: contributing.md
        - Developer Setup: developing.md
        - Code Style: code-style.md
theme:
    name: material
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
