site_name: Groundwork
site_url: https://groundwork.commonknowledge.coop/
repo_url: https://github.com/commonknowledge/groundwork/
nav:
  - Home: index.md
  - Guides:
      - Data Pipeline: guides/data-pipeline.md
  - Reference:
      - Core:
          - Data sources: api/groundwork.core.datasources.md
          - Cron tasks: api/groundwork.core.cron.md
          - Utilities:
              - Cache utils: api/groundwork.core.cache.md
              - Template utils: api/groundwork.core.template.md
      - Geo:
          - Map Components: components/map.components.md
          - UK Geographical Data:
              - Postcode Geolocation: api/groundwork.geo.territories.uk.postcodes.md
              - Parliament API: api/groundwork.geo.territories.uk.parliament.md
  - Contributing:
      - Contribution Guidelines: contributing.md
      - Developer Setup: developing.md
      - Code Style: code-style.md
theme:
  name: material
  logo: img/logo.jpg
  favicon: img/logo.jpg
  custom_dir: docs/overrides
  font:
    text: IBM Plex Sans
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/commonknowledge
