# Generated by Django 3.2.9 on 2021-12-02 20:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SomeRelatedModel",
            fields=[
                ("last_sync_time", models.DateTimeField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SomeSyncedModel",
            fields=[
                ("last_sync_time", models.DateTimeField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("required_value", models.CharField(max_length=128)),
                ("optional_value", models.CharField(max_length=128, null=True)),
                (
                    "embedded",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test.somerelatedmodel",
                    ),
                ),
                (
                    "m2m_relationship",
                    models.ManyToManyField(
                        related_name="m2m_of", to="test.SomeRelatedModel"
                    ),
                ),
                (
                    "optional_relationship",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optional_of",
                        to="test.somerelatedmodel",
                    ),
                ),
                (
                    "recursive_relationship",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recursive_of",
                        to="test.somesyncedmodel",
                    ),
                ),
                (
                    "required_relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_of",
                        to="test.somerelatedmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
