# Generated by Django 3.2.9 on 2021-11-30 15:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleSyncedModel",
            fields=[
                ("last_sync_time", models.DateTimeField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("comrades", models.ManyToManyField(to="test.ExampleSyncedModel")),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_of",
                        to="test.examplesyncedmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
