name: merge-to-main
on:
  pull_request:
    branches:
      - main
jobs:
  write-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: make bootstrap
      - run: make deploy-docs
