name: merge-to-main
on:
  push:
    branches:
      - main
jobs:
  write-docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/commonknowledge/do-app-baseimage-django-node:364385f9d196a2bbe2d5faea025520cc0316501f
      volumes:
        - "/home/app/.cache:~/.docker/cache"
      env:
        DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
        DEBUG: True
    services:
      db:
        image: kartoza/postgis:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DBNAME: postgres
          POSTGRES_HOSTNAME: postgres
          POSTGRES_PORT: 5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.docker/cache/poetry
          key: do-app-baseimage-django-node:364385f9d196a2bbe2d5faea025520cc0316501f-poetry-${{ hashFiles('poetry.lock') }}
      - run: make install
      - run: .github/bin/wait-for-it.sh db:5432 
      - run: make lint
