name: release
on:
  pull_request:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/commonknowledge/do-app-baseimage-django-node:364385f9d196a2bbe2d5faea025520cc0316501f
      # Workaround for: https://github.com/actions/checkout/issues/211
      options: --user 1001
      volumes:
        - "/home/runner/docker/.cache:/home/app/.cache"
      env:
        DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
        DEBUG: True
        PY_IGNORE_IMPORTMISMATCH: 1
    services:
      db:
        image: kartoza/postgis:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DBNAME: postgres
          POSTGRES_HOSTNAME: postgres
          POSTGRES_PORT: 5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /home/runner/docker/.cache/poetry
          key: do-app-baseimage-django-node:364385f9d196a2bbe2d5faea025520cc0316501f-poetry-${{ hashFiles('poetry.lock') }}
      - run: make install
      - run: .github/bin/wait-for-it.sh db:5432
      - run: make lint
      - run: make prepare-release
        env:
          GITHUB_REF: v1.0.1
      - run: make release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
